#!perl
use Cassandane::Tiny;

# A client that moves its connection to a new local port (RFC 9000 9)
# keeps being answered, at the new port, each time it does.  The new paths
# are routed by the spare connection IDs master registered for the
# connection, and h3migrate closes each old port as it leaves it.
sub test_connection_migration
    ($self)
{
    $self->{caldav}->GetCalendars();

    my $rpath = '/dav/calendars/user/cassandane/Default/migration.ics';
    my $ical = <<~"EOF" =~ s/\r?\n/\r\n/gr;
        BEGIN:VCALENDAR
        VERSION:2.0
        PRODID:-//Cassandane//HttpH3//EN
        BEGIN:VEVENT
        UID:h3-migration\@example.com
        DTSTAMP:20260101T000000Z
        DTSTART:20260101T100000Z
        DURATION:PT1H
        SUMMARY:HTTP/3 connection migration
        END:VEVENT
        END:VCALENDAR
        EOF

    my $put = $self->http3_request(
        method => 'PUT',
        path => $rpath,
        headers => [ 'Content-Type' => 'text/calendar; charset=utf-8' ],
        body => $ical,
    );
    $self->assert_num_equals(201, $put->{status});

    my $run = $self->h3migrate(path => $rpath, migrations => 3,
                               username => 'cassandane');
    my $bodylen = $run->{responses}[0]{bodylen};
    $self->assert($bodylen > 0, 'the first GET returned a body');

    my @ports = ($run->{responses}[0]{port}, @{$run->{migrated}});
    $self->assert_cmp_deeply({
        exit => 0,
        end => undef,
        migrated => [ ignore(), ignore(), ignore() ],
        responses => [ map {
            { status => 200, bodylen => $bodylen, port => $_ }
        } @ports ],
    }, $run);

    my %distinct = map { $_ => 1 } @ports;
    $self->assert_num_equals(4, scalar keys %distinct);
}
